version: '3.8'
services:

  orthia-db:
    image: mariadb:11
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - orthia-db-data:/var/lib/mysql

  apache-web:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "${WEB_PORT}:80"
    environment:
      - DB_HOST=orthia-db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    depends_on:
      - orthia-db

volumes:
  orthia-db-data:
