```yaml
version: '3.9'

services:
  apache-web:
    image: php:8.2-apache
    container_name: apache-web
    ports:
      - "8081:80"
    volumes:
      - ./website:/var/www/html
    depends_on:
      - orthia-db

  orthia-db:
    image: mariadb:11
    container_name: orthia-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: orthia
      MYSQL_USER: orthia
      MYSQL_PASSWORD: orthia
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8082:80"
    environment:
      PMA_HOST: orthia-db
      MYSQL_ROOT_PASSWORD: orthia
    depends_on:
      - orthia-db
```
