version: '1.0'

services:

  apache-webserver:
    build:
      context: .
      dockerfile: Docker-file.yml

    container_name: Orthia-apache

    ports:
      - "81:80"

    volumes:
      - ./website:/usr/local/apache2/htdocs:ro

    restart: unless-stopped

    networks:
      - pandemie-network
